version: '3.3'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: python-poetry-fastapi
    ports:
      - 8002:80
    restart: always
    environment:
      - DATABASE_URL: 'localhost'
      - POSTGRES_USER: 'postgres'
      - POSTGRES_PASSWORD: 'dbuser@123'